
FROM mackeyja92/rustup:stable
COPY cargo_config /.cargo/config
RUN apt-get update && apt-get install -qq gcc gcc-arm-linux-gnueabihf
RUN rustup target add armv7-unknown-linux-gnueabihf

VOLUME /build
WORKDIR /build

#CMD cargo build --target=armv7-unknown-linux-gnueabihf 